### ISSUE TITLE
A new site update has broken the script

### ISSUE THREAD

**Issue by Dyras** [Rsge/GreaterGood-CTG-AutoClicker#1]
Hello! I've been using this script for quite some time now, but today it broke. As it turns out, GreaterGood launched a new site update that looks completely different from the old one and your script doesn't seem to like that.

Any chance you could fix it? :)

**Comment by Rsge** [comment]
Should be done and also up on Greasyfork now, thanks for the heads up : )
I had it running in the background for so long I didn't even notice it wasn't running anymore xD

**Comment by Dyras** [comment]
@Rsge There still seems to be an issue. I've noticed several times on both Edge and Firefox that it doesn't seem to auto-click the ads after 2 hours.

**Comment by Rsge** [comment]
@Dyras 
Ok, this is strange. For me it works perfectly fine, at least as long as the tab is either newly opened or reloaded to start up...
Can you check if you have the newest version (delete the old version and redownload it) and disable all other addons? Maybe also look at the developer console for errors?

**Comment by Dyras** [comment]
It hasn't happened for me today, will try to reproduce it on my server tomorrow!

This user has posted console messages though:
https://greasyfork.org/en/scripts/433055-greatergood-ctg-autoclicker/discussions/174055

**Comment by Rsge** [comment]
Yeah, I saw the review, too. With the console output I think I tracked down the cause of this.
Version 2.1.0 is up on Github now and synced to Greasyfork.
Please try again with this new version and if it doesn't work feel free to reopen this or open a new issue.

**Comment by Rsge** [comment]
I changed the commit msg., realized the spelling mistake 😅
